// =============================================
// QR EXPORT UTILITIES — Client-side only
// =============================================

export type ExportFormat = "png" | "svg" | "jpeg" | "pdf" | "4k";

/**
 * Export the QR code SVG element as various formats
 */
export async function exportQR(format: ExportFormat, svgElementId: string = "qr-svg") {
  const svgEl = document.getElementById(svgElementId) as SVGSVGElement | null;
  if (!svgEl) return;

  const svgData = new XMLSerializer().serializeToString(svgEl);

  if (format === "svg") {
    download(new Blob([svgData], { type: "image/svg+xml" }), "qr-launchpad.svg");
    return;
  }

  const exportSize = format === "4k" ? 2048 : 1024;
  const canvas = await svgToCanvas(svgData, exportSize);

  if (format === "pdf") {
    await exportAsPDF(canvas);
    return;
  }

  const mimeType = format === "jpeg" ? "image/jpeg" : "image/png";
  const ext = format === "jpeg" ? "jpg" : format === "4k" ? "qr-4k.png" : "png";
  canvas.toBlob((blob) => {
    if (blob) download(blob, `qr-launchpad.${ext}`);
  }, mimeType, 0.97);
}

async function svgToCanvas(svgData: string, size: number): Promise<HTMLCanvasElement> {
  return new Promise((resolve) => {
    const img = new Image();
    const blob = new Blob([svgData], { type: "image/svg+xml" });
    const url = URL.createObjectURL(blob);
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = size;
      canvas.height = size;
      const ctx = canvas.getContext("2d")!;
      ctx.drawImage(img, 0, 0, size, size);
      URL.revokeObjectURL(url);
      resolve(canvas);
    };
    img.src = url;
  });
}

async function exportAsPDF(canvas: HTMLCanvasElement) {
  // Dynamic import to avoid SSR issues
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const imgData = canvas.toDataURL("image/png");
  // Center QR on A4 (210×297mm), 120mm square
  const margin = (210 - 120) / 2;
  pdf.addImage(imgData, "PNG", margin, 40, 120, 120);
  pdf.setFontSize(12);
  pdf.setTextColor(100);
  pdf.text("Generated by QR Launchpad · qr-launchpad.vercel.app", 105, 180, { align: "center" });
  pdf.save("qr-launchpad.pdf");
}

export async function copyQRToClipboard(svgElementId: string = "qr-svg"): Promise<boolean> {
  try {
    const svgEl = document.getElementById(svgElementId) as SVGSVGElement | null;
    if (!svgEl) return false;
    const svgData = new XMLSerializer().serializeToString(svgEl);
    const canvas = await svgToCanvas(svgData, 512);
    return new Promise((resolve) => {
      canvas.toBlob(async (blob) => {
        if (!blob) { resolve(false); return; }
        try {
          await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
          resolve(true);
        } catch { resolve(false); }
      });
    });
  } catch { return false; }
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
