// =============================================
// QR EXPORT UTILITIES — Uses qr-code-styling's
// native download() for reliable cross-platform export
// =============================================

export type ExportFormat = "png" | "svg" | "jpeg" | "pdf" | "4k";

/**
 * Export from a raw SVG element (fallback path, used for legacy SVG captures).
 * Renders to canvas via Blob URL — avoids CORS issues entirely.
 */
async function svgElementToCanvas(svgEl: SVGSVGElement, size: number): Promise<HTMLCanvasElement> {
  // Inline all image hrefs as data URIs to avoid tainted canvas issues
  const cloned = svgEl.cloneNode(true) as SVGSVGElement;
  const images = cloned.querySelectorAll("image");
  await Promise.all(Array.from(images).map(async (img) => {
    const href = img.getAttribute("href") || img.getAttribute("xlink:href") || "";
    if (href.startsWith("data:")) return; // already inlined
    try {
      const res = await fetch(href, { mode: "no-cors" });
      const blob = await res.blob();
      const dataUrl = await blobToDataUrl(blob);
      img.setAttribute("href", dataUrl);
    } catch {
      img.remove(); // remove broken image rather than blocking export
    }
  }));

  const svgData = new XMLSerializer().serializeToString(cloned);
  return new Promise((resolve, reject) => {
    const img = new Image();
    const blob = new Blob([svgData], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = size;
      canvas.height = size;
      const ctx = canvas.getContext("2d")!;
      ctx.fillStyle = "#FFFFFF";
      ctx.fillRect(0, 0, size, size);
      ctx.drawImage(img, 0, 0, size, size);
      URL.revokeObjectURL(url);
      resolve(canvas);
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error("Failed to render SVG to canvas"));
    };
    img.src = url;
  });
}

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

/**
 * Primary export path — uses the qr-code-styling instance directly.
 * This avoids all html-to-image CORS issues by letting the library handle rendering.
 */
export async function exportQRFromInstance(
  qrInstance: any,
  format: ExportFormat,
  bgColor: string
): Promise<void> {
  if (!qrInstance) throw new Error("QR instance not ready");

  if (format === "svg") {
    await qrInstance.download({ name: "qr-launchpad", extension: "svg" });
    return;
  }

  if (format === "pdf") {
    // Get PNG from instance then wrap in PDF
    const rawBlob: Blob = await qrInstance.getRawData("png");
    const dataUrl = await blobToDataUrl(rawBlob);
    const { jsPDF } = await import("jspdf");
    const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    pdf.addImage(dataUrl, "PNG", 45, 40, 120, 120);
    pdf.setFontSize(11);
    pdf.setTextColor(100);
    pdf.text("Generated by QR Launchpad · digitalheroesco.com", 105, 180, { align: "center" });
    pdf.save("qr-launchpad.pdf");
    return;
  }

  if (format === "4k") {
    await qrInstance.download({ name: "qr-launchpad-4k", extension: "png" });
    return;
  }

  // PNG or JPEG
  const ext = format === "jpeg" ? "jpg" : "png";
  await qrInstance.download({ name: "qr-launchpad", extension: ext });
}

/**
 * Fallback: export from the composite wrapper element using html-to-image.
 * Used when a graphic frame is active (can't use qr-code-styling alone).
 */
export async function exportQRFromElement(
  el: HTMLElement,
  format: ExportFormat,
  bgColor: string
): Promise<void> {
  const { toPng, toSvg, toJpeg } = await import("html-to-image");

  const options = {
    pixelRatio: format === "4k" ? 4 : 2,
    backgroundColor: format === "jpeg" ? bgColor : undefined,
    skipFonts: false,
    // Bypass cross-origin images by using a custom fetch
    fetchRequestInit: { mode: "cors" as RequestMode },
  };

  let url = "";
  if (format === "svg") {
    url = await toSvg(el, options);
  } else if (format === "jpeg") {
    url = await toJpeg(el, { ...options, quality: 0.97 });
  } else {
    url = await toPng(el, options);
  }

  if (format === "pdf") {
    const { jsPDF } = await import("jspdf");
    const pdf = new jsPDF("p", "px", [el.offsetWidth, el.offsetHeight]);
    pdf.addImage(url, "PNG", 0, 0, el.offsetWidth, el.offsetHeight);
    pdf.save("qr-launchpad-design.pdf");
    return;
  }

  const ext = format === "4k" ? "png" : format;
  triggerDownload(url, `qr-launchpad-design.${ext}`);
}

function triggerDownload(url: string, filename: string) {
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}

/**
 * Copy QR code to clipboard as PNG.
 */
export async function copyQRToClipboard(qrInstance: any): Promise<boolean> {
  if (!qrInstance) return false;
  try {
    const rawBlob: Blob = await qrInstance.getRawData("png");
    await navigator.clipboard.write([new ClipboardItem({ "image/png": rawBlob })]);
    return true;
  } catch {
    return false;
  }
}
